### ISSUE TITLE
View file doesn't work when triggered from the file manager

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#1191] opened 2022-08-09 15:42 UTC
**Describe the bug**
View file doesn't work when triggered from the file manager.

It says the file is not part of the pipeline and therefore fails to open the file. Also, double clicking the file in the pipeline editor when the pipeline editor is in read-only mode should open the file preview page but it doesn't. This might be related to the fact that the file cannot be found as being part of the pipeline.

**Expected behavior**
In the pipeline editor view, if the file is assigned to a step in the pipeline it should be open-able in the file preview page through the file manager.

**To Reproduce**

1. Create a job
2. Open pipeline run of the job
3. Double click a file (in the file manager on the left hand side) that's assigned in the pipeline to a step or right click on that file in the file manager and click "View"

Note that the right click "View" failure happens in both read-only and edit-mode pipeline editor. Since the default behavior of double click in the edit-mode pipeline editor is to open the file in JupyterLab the double click failure case only happens on the read-only pipeline editor page.

**Screenshots**
![image](https://user-images.githubusercontent.com/1309307/183697194-4465625d-7963-4f65-9dbb-d955a8168216.png)

**Environment**
- OS (e.g. macOS): Linnux
- Browser (e.g. Chrome): Brave
- Orchest's version (in the settings page): v2022.08.1

**Comment by yannickperrenet** [comment] 2022-08-09 15:54
Duplicate of #1152

**Closed by yannickperrenet** 2022-08-09 15:54 UTC
Labels: bug

**Comment by ricklamers** [comment] 2022-08-09 15:56
Oops.
