### ISSUE TITLE
Cross projects jobs view

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#738] opened 2022-02-23 08:38 UTC
**Describe the feature you'd love to have in Orchest**

Having a general understanding of what jobs are running or are going to run (and when) becomes difficult as the number of projects and jobs increases. A way to having a cross projects view of that would help. Things that should be easier to know with the blink of an eye:

- how many active cronjobs are there?
- what's the timeline for the next cronjobs that are going to be triggered? (i.e. the N closest cronjobs that are going to run)
- how many jobs have some runs that are running right now?
- ...

**Comment by yannickperrenet** [comment] 2022-02-23 17:31
Duplicate of #485.

I do like extending the scope of the dashboard though and showing additional information, e.g. not only running jobs but also a timeline for next running jobs.

**Closed by yannickperrenet** 2022-02-23 17:31 UTC
Labels: new feature request
