### ISSUE TITLE
Run all step shortcut

### ISSUE THREAD

**Issue by kingabzpro** [orchest/orchest#428] opened 2021-08-19 11:53 UTC
**Describe the solution you'd like**  
is there a way to run all step with shortcut? when selecting and panning 20+ steps can be frustrating

**What does your solution aim to solve?**  
ease of running all the steps at once

**Describe alternatives you've considered**  
Add more shortcuts just like ctrl + alt + enter to run all.

**Comment by yannickperrenet** [comment] 2021-08-19 11:55
Thanks for opening an issue. I definitely like the idea!

Duplicate of #327.

**Closed by yannickperrenet** 2021-08-19 11:55 UTC
Labels: duplicate, improvement

**Comment by ricklamers** [comment] 2021-08-19 11:57
A difference is that @kingabzpro is proposing a _shortcut_ instead of a button. I'll add that to #327 to keep the conversation focused.
