### ISSUE TITLE
Dialog overflow when creating a job

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#547] opened 2021-11-11 13:38 UTC
**Describe the bug**  
Dialog doesn't overflow when creating a job.

**To Reproduce**  

1. Go to Jobs page
2. Create a new job
3. (make sure you have multiple pipelines to choose from)
4. Observe that the select dropdown is contained in the dialog box.

**Expected behavior**  
It should overflow the dialog. A simple `overflow: visible` on the outer dialog element fixes this.

**Environment**

- OS: Linux
- Browser: Brave
- Version: 2021.11.1
- Environment: prod, cloud

**Comment by yannickperrenet** [comment] 2021-11-12 17:51
Duplicate of #413

**Closed by yannickperrenet** 2021-11-12 17:51 UTC
Labels: bug
