### ISSUE TITLE
Incorrect warning when using web updater

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#137] opened 2021-02-02 08:56 UTC
`Using Orchest whilst updating is NOT recommended.` should not be displayed when using the web updater.

**Comment by yannickperrenet** [comment] 2021-02-02 09:09
Why should it not be displayed? The functionality is different then before. We used to shutdown containers whilst now we don't and so Orchest now is usable during the update in contrast to before.

**Comment by yannickperrenet** [comment] 2021-02-02 09:12
I consider this as not a bug and will close the issue. Feel free to reopen if you don't agree.

**Closed by yannickperrenet** 2021-02-02 09:12 UTC
Labels: bug
